### ISSUE TITLE
cannot cmake

### ISSUE THREAD

**Issue by mpkuse** [cr333/usac-cmake#1]
Hi,
I tried to clone your code on my Ubuntu 16.04. I have the BLAS lib already setup with cmake. 

```
git clone ... 
cd usac-cmake
mkdir build 
cmake ..
```

Here is my error:
-- use C interface for Lapack
-- use c interaface for Blas
-- Found /usr/lib/atlas-base/atlas/libblas.so;/usr/lib/atlas-base/atlas/liblapack.so in /usr/lib/atlas-base/atlas
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CONFIG++_INCLUDE_DIR
   used as include directory in directory /home/mpkuse/Downloads/usac-cmake/src
   used as include directory in directory /home/mpkuse/Downloads/usac-cmake/src
   used as include directory in directory /home/mpkuse/Downloads/usac-cmake/src
CONFIG++_LIBRARY
    linked by target "USAC" in directory /home/mpkuse/Downloads/usac-cmake/src

-- Configuring incomplete, errors occurred!

Any pointers on fixing this?

**Comment by cr333** [comment]
One of the dependencies of USAC is “[libconfig](https://hyperrealm.github.io/libconfig/)” ([see readme](https://github.com/cr333/usac-cmake/blob/0fd1934b696088b273ac7fe4dea400a07e45475c/readme.txt#L53)), which you seem to not have installed (or CMake cannot find it).

Try installing it and setting CMake’s `CONFIG++_INCLUDE_DIR` variable to the include directory, and `CONFIG++_LIBRARY` to the full path of the “libconfig++.so” library.

**Comment by skcksjhcnsk** [comment]
Hi,in your readme file, I can see that you  run your program in Windows . How do you install libconfig in Windows? Libconfig doesn't seem to support Windows.

**Comment by cr333** [comment]
I don't recall any major issues with libconfig on Windows – their website also explicitly mentions Windows support.

You might find it useful to use libconfig version 1.4.5, which came with the original code distribution:
https://github.com/cr333/usac-cmake/releases/download/USAC-1.0/USAC-1.0-code-and-data.zip

**Comment by skcksjhcnsk** [comment]
> 我不记得 Windows 上的 libconfig 有任何重大问题——他们的网站也明确提到了 Windows 支持。
> 
> 您可能会发现使用 libconfig 版本 1.4.5 很有用，它随原始代码分发一起提供：[https](https://github.com/cr333/usac-cmake/releases/download/USAC-1.0/USAC-1.0-code-and-data.zip) :
> [//github.com/cr333/usac-cmake/releases/download/USAC-1.0/USAC-1.0-code-and -数据.zip](https://github.com/cr333/usac-cmake/releases/download/USAC-1.0/USAC-1.0-code-and-data.zip)

Thanks  for providing the original code and libconfig，but a fatal error occurred when I decompressed it and compiled it with Visual studio 2010
> LINK：fatal error LNK1181：cannot open input file“USAC.lib”.

In fact, I cannot find this "USAC. Lib"anywhere， Did I ignore any work ，or  how should I deal with the files you provided later.

**Comment by cr333** [comment]
I'm afraid I can't help with this. Sorry.

**Comment by skcksjhcnsk** [comment]
I have already solved it，thanks again.
